### ISSUE TITLE
create a rest api route to verify the jwt - POST 

### ISSUE THREAD

**Issue by sreehari2003** [sreehari2003/cvshare.io#23]

**Comment by Arciiix** [comment]
Can you assign it to me? :)

**Comment by sreehari2003** [comment]
> Can you assign it to me? :)

there already exits a function called isAuth in the middleware folder you could refer that

**Comment by Arciiix** [comment]
Do you mean just creating a route which would validate the cached JWT token and return 200 when it's valid and 401 when it's not?

**Comment by sreehari2003** [comment]
> Do you mean just creating a route which would validate the cached JWT token and return 200 when it's valid and 401 when it's not?

yes !are you the guy who messged me via linkid in ? 
when we load a protected page we need to verify the user i belive we can do this via sending the token to server and verifying it do you have any other idea in mind ?  also when you are sendinf the reposnse there is function called serverresponse dont forger to use that

**Comment by Arciiix** [comment]
@sreehari2003 I will get to know your project at first (the file structure etc.), is that alright?

**Comment by sreehari2003** [comment]
> @sreehari2003 no, I'm not him hahah, I wanted to make one of my first contributions and was just browsing through GitHub explore and found your project
> 
> And yes, I guess that's a good thing, and as you created it already, when it comes to the protected routes that need auth, you can just use the verify jwt middleware :)

yes you got it. btw if you are interested in frontend you could do that as well i am a begineer guy. also when you are commiting dont forget to use convetional commit mesages  https://www.conventionalcommits.org/en/v1.0.0/

**Comment by sreehari2003** [comment]
> @sreehari2003 I will get to know your project at first (the file structure etc.), is that alright?

ok

**Comment by Arciiix** [comment]
@sreehari2003 unfortunately it seems like there are some typing errors (such as User is not exported from express) and I don't have MongoDB installed so that I wouldn't be able to test it, so I think I will resolve this issue when I have some more free time. Is it okay if I for example fix some typos for you? Because I saw some

**Comment by Arciiix** [comment]
@sreehari2003 The thing is that I created the REST route to verify the JWT, but I cannot test it, because the pnpm package manager doesn't also work 😂
So I will make a pull request, and then the question becomes if you can test if it works?

**Comment by Arciiix** [comment]
@sreehari2003 
If it works, then you can merge #25  (the typos fixes + the route)
If it doesn't, then you can merge #24 (just the typos)
Sorry for the inconvenience
